embedded-assets.md
https://github.com/expo/expo-cli/pull/1745
=> add embedded-assets

deprecating-ar.md
partial step of https://github.com/expo/expo/issues/8371
=> add deprecating-ar page

remove-alpha-channel.md
Addresses this issue: https://github.com/expo/expo-cli/issues/2225
I am going to add a link to this FYI in the CLI to give developers more context/solutions if they encounter this error.
=> [fyi] Adds FYI on alpha channel

project-page.md
Reading the doc and notice a missing word. Cheers!
=> Missing word

android-r.md
Follow up from https://github.com/expo/expo/pull/12307
=> [android-r] add section on MAC address

black-screen-before-splash.md
ref: https://github.com/expo/expo/issues/11968#issuecomment-852382630
=> [splash] create splash screen black screen fyi

eas-vcs-workflow.md
- removed a duplicated bullet point (different wording, exact same concept)
=> [docs] EAS-VSC Wokflow - minor typo fixes

missing-native-module.md
Adds missing-native-module.md for https://github.com/expo/expo/pull/18465
resolves ENG-6097
=> add missing-native-module

firebase-migration-guide.md
Recently, some issues with the existing content of the guide were reported internally.
This PR
- updates the instructions to redirect the developer to RNFB docs for adding config plugin(s) and providing paths to service JSON files
- Other minor verbiage fixes
=> Update Firebase Migration guide

auth-proxy-migration.md
=> Add auth proxy migration guide

eas-config-mismatch.md
fyi page that could be linked in error here https://github.com/expo/eas-build/pull/228
=> add fyi about mismatched config values

why-constants-expoconfig.md
=> Add explanation about migrating from Constants.manifest to expoConfig

redirects/dev-build
=> [redirect] redirect for dev build

bumping-ios-build-number.md
seems like a nice thing to mention
=> mention automatic version bump

cryptic-error-eas.md
Forum links redirects to the old forums. This PR updates the link to our Discord.
=> [fyi] Fix link in cryptic-error-eas.md

barcode-scanner-to-expo-camera.md
Add a page that demonstrates replacing `expo-barcode-scanner` with `expo-camera`
=> Add barcode scanner to camera migration

assets/sso-setup-microsoft/config-flag-migration.md, eas-vcs-workflow.md, embedded-assets.md, firebase-js-auth-setup.md, firebase-migration-guide.md, legacy-notifications-to-expo-notifications.md, provisioning-profile-missing-capabilities.md, remove-alpha-channel.md, sentry-expo-migration.md, wsl.md
This PR fixes typos and incorrect grammar usage in multiple guides.
=> Fix typos in multiple guides

README.md
The current version of **README.md** is a bit outdated and doesn't follow our writing style guide patterns and formatting. This PR fixes issues such as typos, incorrect grammar usage, incorrect formatting, etc.
See the diff.
=> Fix outdated info and formatting issues in README.md

apns-entitlement-sdk-51.md
See [ENG-12643](https://linear.app/expo/issue/ENG-12643/[notifications][ios]-determine-steps-to-remove-apns-entitlement-for)
=> docs: update APNS entitlement FYI

sso-setup-google-ws.md, sso-setup-microsoft.md, sso-setup-okta.md, sso-setup-onelogin.md
Small change to each of the IdP setup guides for self-service SSO signup
Related PR: https://github.com/expo/expo/pull/29855
=> SSO self service setup changes

apple-app-specific-password.md
https://exponent-internal.slack.com/archives/C018QNC2LV6/p1721090886185809
=> Improve Apple app specific password docs

already-on-app-stores.md
PR improves docs for [already-on-app-stores.md](https://github.com/expo/fyi/blob/main/already-on-app-stores.md)
=> Tidy up `already-on-app-stores` fyi

router-navigation-deps.md
Add `router-navigation-deps.md` to provide instructions on how to resolve Expo Router dep conflicts
=> Add router-navigation-deps.md

apple-2fa-sms-issues-workaround.md
https://exponent-internal.slack.com/archives/C017N0N99RA/p1733768696103679
=> Add doc explaining workaround for Apple 2FA SMS issues

android-app-size.md
"revert back"
"reply back"
"8am in the morning"
"naked with no clothes on"
:)
=> docs: minor grammar fix

edge-to-edge-system-bars.md
Will be used in https://github.com/expo/expo/pull/34478 comments
=> Add edge-to-edge + system bars document

subscribing-to-app-events.md
in response to https://github.com/expo/expo/pull/36358#issuecomment-2831441149
=> docs: add page for app-event-subscribers

wsl.md
Update to what's detailed in the linked Microsoft docs, as the initially proposed version did not work.
=> Update command for opening up Hyper-V firewall

eas-update-update-rollouts.md
As requested in https://github.com/expo/eas-cli/pull/3068.
=> Add fyi about update rollouts
