- README.md
the example link is redirected to a wrong address. now it is fixed
> fix README linking error

- prebuilding.md
Provide a bunch of written resources that can be linked to from READMEs and setup guides. Perhaps these are better suited for the expo docs.
> Created prebuilding guide

- cryptic-error-eas.md
people using `eas-cli` will sometimes get unhelpful errors and it's really hard to figure what's going on, especially if all the error says is `received unexpected null`. With oclif, we can pass in the `DEBUG=*` env var to get a stack trace, which will help immensely to track down the problem.
> add cryptic-error.md

- expo-app-auth-deprecated.md
Add a guide for migrating off of expo-app-auth and onto expo-auth-session.
> Create expo-app-auth deprecated docs

- bundle-identifier.md
This fixes the Expo client application's bundle identifier from
`host.exp.exponent` to `host.exp.Exponent` and also adds a reference
link for verification. The lowercase bundle id doesn't work with `xcrun
simctl get_app_container`.
> Fix the capitalization of client app's bundle ID

- android-navigation-bar-visible-deprecated.md
Currently this doc suggests invalid JSON for the EAS build process. Expo doctor currently complains about the suggested format in this FYI document. @EvanBacon I'm assuming the booleans were accidentally wrapped in quotes when drafting this help document? Or is Expo doctor wrong? 
Logs from EAS Build:
```
Running "expo doctor"
[stderr] [21:40:55] Error: Problem validating fields in app.json. Learn more: https://docs.expo.dev/workflow/configuration/
[stderr] [21:40:55]  • Field: androidStatusBar.hidden - should be boolean.
```
> [docs] fix invalid JSON suggestions

- firebase-migration-guide.md
Pretty sure that the `const app = initializeApp(config)` line should be in the web snippet.
> fix: typo in firebase-migration-guide.md

- firebase-migration-guide.md
It has caused some confusion and failed iOS builds for some developers when they have `expo-firebase-core` installed directly in their project.
This PR adds a small section to indicate that the package must be removed if explicitly installed to avoid unnecessary build failures.
It also updates the link of development build getting started guide.
> [firebase-migration-guide]: Add a section to remove expo-firebase-core

- prebuilt-modules.md
Closes ENG-6730.
By adding a note that modules do not have prebuilt binaries as @tsapeta shared context on what was the underlying issue.
> Add a note about prebuilt modules

- auth-proxy-migration.md
Linkt to `manifestUrl` is broken as reported by a user in Discord. This PR fixes that link.
> Fix link in auth-proxy-migration.md

- expo-modules-gradle8-migration.md
if developers have custom expo-modules generated from `create-expo-module`, they may see some errors/warnings due to gradle 8 in sdk 49. This page adds some instructions for people to have gradle 8 compatibility support.
Preview: https://github.com/expo/fyi/blob/%40kudo/expo-module-gradle8/expo-modules-gradle8-migration.md
> Add expo-modules-gradle8-migration.md

- eas-update-missing-headers.md
A lot of users debugging EAS Update will receive a 'missing headers' error message from www if their app is not configured properly. Linking to this `expo.fyi`  in the `www` error will give folks a starting point to debug, depending on their use case
> eas update: add missing headers guide

- firebase-js-auth-setup.md
This page is now redundant for users of Firebase SDK v10 and above, however it should be left in this repo as majority of SDK users are on v9 and below. I have rewritten the introduction for clarity.
- Closes #122 
- See discussion in firebase/firebase-js-sdk#7425
I will also update the tutorial in the docs with this (https://docs.expo.dev/guides/using-firebase/#using-firebase-js-sdk).
> Update firebase-js-auth-setup.md with release of Firebase SDK 10

- firebase-js-auth-setup.md
Close #127 
As brought up and info shared in the #127, Firebase JS SDK from v10.3.0 and above requires explicitly importing AsyncStorage library. They have also removed the automatic persistence management for React Native from the JS SDK.
This PR
- Adds a new top-level section about setting up persistence when using v10.3.0
- Also adds a new top-level section to differentiate the steps already mentioned for v9 and below
> Add info about v10.3.0 Firebase JS SDK auth persistence

- android-navigation-bar-visible-deprecated.md
Hi there! I __think__ `androidNavigationBar.visible = "sticky-immersive"` was using an `overlay-swipe` behaviour by default, so if we want to make it replicate it with `expo-navigation-bar` we might wanna recommend `overlay-swipe` there as well... I guess?  
- [Related Twitter discussion here](https://twitter.com/mazzarolomatteo/status/1622859164325126144)  
- [PR in an app where I'm using this change](https://github.com/mmazzarolo/breathly-app/pull/100/commits/8ab511bea781f69bed7524286d26480b31d7a3eb)
> Use `overlay-swipe` for `sticky-immersive`

- start.md
Fixes #125 
- By adding links to Development build with EAS and compiling app locally.
> [docs] Create a start.md to add links about development builds

- prebuild-without-npm-access.md
Prebuild generally uses `@expo/package-manager` for NPM access, which respects .npmrc, but the template download step doesn't. This doc describes how to specify a template via Github link or local download. This doc can help folks who are using these tools on a network that exclusively accesses NPM via a private repo.
> FYI for using prebuild, etc without NPM access

- sentry-expo-migration.md
When reading the Expo's sentry docs for SDK 50 (https://docs.expo.dev/guides/using-sentry/) I've come across this step of wrapping the App with `Sentry.wrap()`. This is missing from the migration guide.
> docs: Add the wrapping process in sentry-expo-migration.md

- barcode-scanner-to-expo-camera.md
The prop is `barcodeTypes` not `barCodeTypes`
> Fix typo on prop in barcode scanner to camera migration example code

- barcode-scanner-to-expo-camera.md
I've noticed that the case of `onBarCodeScanned` was changed to `onBarcodeScanned` and propose to do the same with the handle function 🎉.
> chore(docs): update case of the handle function like expo-camera

- advice-dont-ask-about-solutions.md
- advice-dont-ask-to-ask.md
- advice-dont-wait-to-ask.md
Currently, we're receiving a lot of messages on Discord that ultimately go unanswered. This often is caused by four main reasons:
- The poster asked to ask
- The poster asked about a solution without stating their problem
- The poster waited to ask
- The poster didn't give an issue report for an issue
This PR proposes to add three advice documents to this repo that can be used to reply to messages fitting the first three reasons above.
The fourth reason is excluded since it requires us to write a longer and more comprehensive document that would have to encompass a lot of advice on how to write a proper issue report (like an issue template++)
Most of these documents are based on existing docs that are out in the internet,
but have been rephrased to:
- repeat the advice they contain and …
> docs: Add meta advice about questions (mostly for Discord)

- apple-2fa-sms-issues-workaround.md
Include a description of `rm -rf ~/.app-store` workaround as well
> update 2fa workaround docs

- resolving-dependency-issues.md
We can add instructions for Bun here as well. It seems like not having this in Bun <1.2.20 with isolated dependencies and in some lockfile conditions (moving from hoisted to isolated) can cause duplication otherwise, that's then captured by the lockfile.
Adding instructions for Bun to disable this is quite straightforward
> Add instructions to disable auto-installing peers for Bun

- resolving-dependency-issues.md
This document is a bit long and intimidating, and not everyone needs to first understand why dependency issues occur. Instead, we can collapse the explanation section and make sure the steps to resolve dependency issues are higher up.
> Resolving Dependency Issues: Collapse explanation into a `<details>`
